version: "3.8"

services:
  janus:
    build: ./meetecho
    container_name: janus
    networks:
      - internal_net
    restart: unless-stopped
    extra_hosts:
      - "umbrel:host-gateway"
    volumes:
      - ./meetecho/janus/html:/usr/local/share/janus/demos
      - ./meetecho/janus/config:/usr/local/etc/janus
      - ./meetecho/janus/videos:/usr/local/share/janus/video
      - ./meetecho/janus/log:/usr/local/var/log
    ports:
      - "8088:8088"
      - "7088:7088"
      - "7888:7888"
      - "8188:8188"
      - "5004:5004/udp"
      - "5010:5010/udp"

  web:
    image: python:3.11-slim
    container_name: janus-web
    working_dir: /srv
    volumes:
      - ./meetecho/janus/html:/srv
    command: python -m http.server 8081
    networks:
      - internal_net
    restart: unless-stopped
    extra_hosts:
      - "umbrel:host-gateway"
    ports:
      - "8081:8081"

  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: ffmpeg
    restart: unless-stopped
    command: [
      "-re", "-i", "http://umbrel:8080/?action=stream",
      "-vf", "scale=854:480",
      "-c:v", "vp8", "-b:v", "1M", "-an",
      "-payload_type", "96",
      "-f", "rtp", "rtp://janus:5010"
    ]
    networks:
      - internal_net
    depends_on:
      - janus
    extra_hosts:
      - "umbrel:host-gateway"

networks:
  internal_net:
    driver: bridge
